export enum ShippingCostLevel {
  ORDER = 'ORDER',
  QUANTITY = 'QUANTITY',
  WEIGHT = 'WEIGHT',
}

export enum EFeeLevel {
  PRODUCT = 'PRODUCT',
  VARIANT = 'VARIANT',
}

export enum StateStatus {
  FAILED = 'failed',
  PENDING = 'pending',
  PROCESSED = 'processed',
  PROCESSING = 'processing',
}

export enum SubscriptionPlans {
  FREE = 'free',
  PRO = 'pro',
}

export enum RecalculateCostsType {
  COGS_HANDLING_FEES = 'handling_fees_cogs',
  SHIPPING_COSTS = 'shipping_costs',
  TRANSACTION_FEES = 'transaction_fees',
}

export enum DefaultRoutes {
  HOME = '/dashboard',
  ONBOARD = '/onboard',
  PRICING = '/pricing',
}

export enum NotificationType {
  COGS_HANDLING_FEES_EXPORT = 'cogs-handling-fees-export',
  COGS_HANDLING_FEES_IMPORT = 'cogs-handling-fees-import',
}

export const defaultRegionUUID = 'default';

export const orderStatusList = [
  {
    value: 'AUTHORIZED',
    labelKey: 'page.common.orderStatus.authorized',
    label: 'Authorized',
  },
  {
    value: 'PAID',
    labelKey: 'page.common.orderStatus.paid',
    label: 'Paid',
  },
  {
    value: 'PARTIALLY_PAID',
    labelKey: 'page.common.orderStatus.partiallyPaid',
    label: 'Partially Paid',
  },
  {
    value: 'PARTIALLY_REFUNDED',
    labelKey: 'page.common.orderStatus.partiallyRefunded',
    label: 'Partially Refunded',
  },
  {
    value: 'PENDING',
    labelKey: 'page.common.orderStatus.pending',
    label: 'Pending',
  },
  {
    value: 'VOIDED',
    labelKey: 'page.common.orderStatus.voided',
    label: 'Voided',
  },
];

export const ShippingCostLevelList = [
  {
    label: 'Quantity',
    value: ShippingCostLevel.QUANTITY,
  },
  {
    label: 'Weight',
    value: ShippingCostLevel.WEIGHT,
  },
  {
    label: 'Order',
    value: ShippingCostLevel.ORDER,
  },
];

export const countries = [
  { value: 'AD', label: 'Andorra', icon: '🇦🇩' },
  { value: 'AE', label: 'United Arab Emirates', icon: '🇦🇪' },
  { value: 'AF', label: 'Afghanistan', icon: '🇦🇫' },
  { value: 'AG', label: 'Antigua and Barbuda', icon: '🇦🇬' },
  { value: 'AI', label: 'Anguilla', icon: '🇦🇮' },
  { value: 'AL', label: 'Albania', icon: '🇦🇱' },
  { value: 'AM', label: 'Armenia', icon: '🇦🇲' },
  { value: 'AO', label: 'Angola', icon: '🇦🇴' },
  { value: 'AQ', label: 'Antarctica', icon: '🇦🇶' },
  { value: 'AR', label: 'Argentina', icon: '🇦🇷' },
  { value: 'AS', label: 'American Samoa', icon: '🇦🇸' },
  { value: 'AT', label: 'Austria', icon: '🇦🇹' },
  { value: 'AU', label: 'Australia', icon: '🇦🇺' },
  { value: 'AW', label: 'Aruba', icon: '🇦🇼' },
  { value: 'AX', label: 'Åland Islands', icon: '🇦🇽' },
  { value: 'AZ', label: 'Azerbaijan', icon: '🇦🇿' },
  { value: 'BA', label: 'Bosnia and Herzegovina', icon: '🇧🇦' },
  { value: 'BB', label: 'Barbados', icon: '🇧🇧' },
  { value: 'BD', label: 'Bangladesh', icon: '🇧🇩' },
  { value: 'BE', label: 'Belgium', icon: '🇧🇪' },
  { value: 'BF', label: 'Burkina Faso', icon: '🇧🇫' },
  { value: 'BG', label: 'Bulgaria', icon: '🇧🇬' },
  { value: 'BH', label: 'Bahrain', icon: '🇧🇭' },
  { value: 'BI', label: 'Burundi', icon: '🇧🇮' },
  { value: 'BJ', label: 'Benin', icon: '🇧🇯' },
  { value: 'BL', label: 'Saint Barthélemy', icon: '🇧🇱' },
  { value: 'BM', label: 'Bermuda', icon: '🇧🇲' },
  { value: 'BN', label: 'Brunei Darussalam', icon: '🇧🇳' },
  { value: 'BO', label: 'Bolivia (Plurinational State of)', icon: '🇧🇴' },
  { value: 'BQ', label: 'Bonaire, Sint Eustatius and Saba', icon: '🇧🇶' },
  { value: 'BR', label: 'Brazil', icon: '🇧🇷' },
  { value: 'BS', label: 'Bahamas', icon: '🇧🇸' },
  { value: 'BT', label: 'Bhutan', icon: '🇧🇹' },
  { value: 'BV', label: 'Bouvet Island', icon: '🇧🇻' },
  { value: 'BW', label: 'Botswana', icon: '🇧🇼' },
  { value: 'BY', label: 'Belarus', icon: '🇧🇾' },
  { value: 'BZ', label: 'Belize', icon: '🇧🇿' },
  { value: 'CA', label: 'Canada', icon: '🇨🇦' },
  { value: 'CC', label: 'Cocos (Keeling) Islands', icon: '🇨🇨' },
  { value: 'CD', label: 'Congo, Democratic Republic of the', icon: '🇨🇩' },
  { value: 'CF', label: 'Central African Republic', icon: '🇨🇫' },
  { value: 'CG', label: 'Congo', icon: '🇨🇬' },
  { value: 'CH', label: 'Switzerland', icon: '🇨🇭' },
  { value: 'CI', label: "Côte d'Ivoire", icon: '🇨🇮' },
  { value: 'CK', label: 'Cook Islands', icon: '🇨🇰' },
  { value: 'CL', label: 'Chile', icon: '🇨🇱' },
  { value: 'CM', label: 'Cameroon', icon: '🇨🇲' },
  { value: 'CN', label: 'China', icon: '🇨🇳' },
  { value: 'CO', label: 'Colombia', icon: '🇨🇴' },
  { value: 'CR', label: 'Costa Rica', icon: '🇨🇷' },
  { value: 'CU', label: 'Cuba', icon: '🇨🇺' },
  { value: 'CV', label: 'Cabo Verde', icon: '🇨🇻' },
  { value: 'CW', label: 'Curaçao', icon: '🇨🇼' },
  { value: 'CX', label: 'Christmas Island', icon: '🇨🇽' },
  { value: 'CY', label: 'Cyprus', icon: '🇨🇾' },
  { value: 'CZ', label: 'Czechia', icon: '🇨🇿' },
  { value: 'DE', label: 'Germany', icon: '🇩🇪' },
  { value: 'DJ', label: 'Djibouti', icon: '🇩🇯' },
  { value: 'DK', label: 'Denmark', icon: '🇩🇰' },
  { value: 'DM', label: 'Dominica', icon: '🇩🇲' },
  { value: 'DO', label: 'Dominican Republic', icon: '🇩🇴' },
  { value: 'DZ', label: 'Algeria', icon: '🇩🇿' },
  { value: 'EC', label: 'Ecuador', icon: '🇪🇨' },
  { value: 'EE', label: 'Estonia', icon: '🇪🇪' },
  { value: 'EG', label: 'Egypt', icon: '🇪🇬' },
  { value: 'EH', label: 'Western Sahara', icon: '🇪🇭' },
  { value: 'ER', label: 'Eritrea', icon: '🇪🇷' },
  { value: 'ES', label: 'Spain', icon: '🇪🇸' },
  { value: 'ET', label: 'Ethiopia', icon: '🇪🇹' },
  { value: 'FI', label: 'Finland', icon: '🇫🇮' },
  { value: 'FJ', label: 'Fiji', icon: '🇫🇯' },
  { value: 'FM', label: 'Micronesia (Federated States of)', icon: '🇫🇲' },
  { value: 'FO', label: 'Faroe Islands', icon: '🇫🇴' },
  { value: 'FR', label: 'France', icon: '🇫🇷' },
  { value: 'GA', label: 'Gabon', icon: '🇬🇦' },
  { value: 'GB', label: 'United Kingdom', icon: '🇬🇧' },
  { value: 'GD', label: 'Grenada', icon: '🇬🇩' },
  { value: 'GE', label: 'Georgia', icon: '🇬🇪' },
  { value: 'GF', label: 'French Guiana', icon: '🇬🇫' },
  { value: 'GG', label: 'Guernsey', icon: '🇬🇬' },
  { value: 'GH', label: 'Ghana', icon: '🇬🇭' },
  { value: 'GI', label: 'Gibraltar', icon: '🇬🇮' },
  { value: 'GL', label: 'Greenland', icon: '🇬🇱' },
  { value: 'GM', label: 'Gambia', icon: '🇬🇲' },
  { value: 'GN', label: 'Guinea', icon: '🇬🇳' },
  { value: 'GP', label: 'Guadeloupe', icon: '🇬🇵' },
  { value: 'GQ', label: 'Equatorial Guinea', icon: '🇬🇶' },
  { value: 'GR', label: 'Greece', icon: '🇬🇷' },
  { value: 'GT', label: 'Guatemala', icon: '🇬🇹' },
  { value: 'GU', label: 'Guam', icon: '🇬🇺' },
  { value: 'GW', label: 'Guinea-Bissau', icon: '🇬🇼' },
  { value: 'GY', label: 'Guyana', icon: '🇬🇾' },
  { value: 'HK', label: 'Hong Kong', icon: '🇭🇰' },
  { value: 'HN', label: 'Honduras', icon: '🇭🇳' },
  { value: 'HR', label: 'Croatia', icon: '🇭🇷' },
  { value: 'HT', label: 'Haiti', icon: '🇭🇹' },
  { value: 'HU', label: 'Hungary', icon: '🇭🇺' },
  { value: 'ID', label: 'Indonesia', icon: '🇮🇩' },
  { value: 'IE', label: 'Ireland', icon: '🇮🇪' },
  { value: 'IL', label: 'Israel', icon: '🇮🇱' },
  { value: 'IM', label: 'Isle of Man', icon: '🇮🇲' },
  { value: 'IN', label: 'India', icon: '🇮🇳' },
  { value: 'IO', label: 'British Indian Ocean Territory', icon: '🇮🇴' },
  { value: 'IQ', label: 'Iraq', icon: '🇮🇶' },
  { value: 'IR', label: 'Iran (Islamic Republic of)', icon: '🇮🇷' },
  { value: 'IS', label: 'Iceland', icon: '🇮🇸' },
  { value: 'IT', label: 'Italy', icon: '🇮🇹' },
  { value: 'JE', label: 'Jersey', icon: '🇯🇪' },
  { value: 'JM', label: 'Jamaica', icon: '🇯🇲' },
  { value: 'JO', label: 'Jordan', icon: '🇯🇴' },
  { value: 'JP', label: 'Japan', icon: '🇯🇵' },
  { value: 'KE', label: 'Kenya', icon: '🇰🇪' },
  { value: 'KG', label: 'Kyrgyzstan', icon: '🇰🇬' },
  { value: 'KH', label: 'Cambodia', icon: '🇰🇭' },
  { value: 'KI', label: 'Kiribati', icon: '🇰🇮' },
  { value: 'KM', label: 'Comoros', icon: '🇰🇲' },
  { value: 'KN', label: 'Saint Kitts and Nevis', icon: '🇰🇳' },
  { value: 'KP', label: "Korea (Democratic People's Republic of)", icon: '🇰🇵' },
  { value: 'KR', label: 'Korea, Republic of', icon: '🇰🇷' },
  { value: 'KW', label: 'Kuwait', icon: '🇰🇼' },
  { value: 'KY', label: 'Cayman Islands', icon: '🇰🇾' },
  { value: 'KZ', label: 'Kazakhstan', icon: '🇰🇿' },
  { value: 'LA', label: "Lao People's Democratic Republic", icon: '🇱🇦' },
  { value: 'LB', label: 'Lebanon', icon: '🇱🇧' },
  { value: 'LC', label: 'Saint Lucia', icon: '🇱🇨' },
  { value: 'LI', label: 'Liechtenstein', icon: '🇱🇮' },
  { value: 'LK', label: 'Sri Lanka', icon: '🇱🇰' },
  { value: 'LR', label: 'Liberia', icon: '🇱🇷' },
  { value: 'LS', label: 'Lesotho', icon: '🇱🇸' },
  { value: 'LT', label: 'Lithuania', icon: '🇱🇹' },
  { value: 'LU', label: 'Luxembourg', icon: '🇱🇺' },
  { value: 'LV', label: 'Latvia', icon: '🇱🇻' },
  { value: 'LY', label: 'Libya', icon: '🇱🇾' },
  { value: 'MA', label: 'Morocco', icon: '🇲🇦' },
  { value: 'MC', label: 'Monaco', icon: '🇲🇨' },
  { value: 'MD', label: 'Moldova, Republic of', icon: '🇲🇩' },
  { value: 'ME', label: 'Montenegro', icon: '🇲🇪' },
  { value: 'MF', label: 'Saint Martin (French part)', icon: '🇲🇫' },
  { value: 'MG', label: 'Madagascar', icon: '🇲🇬' },
  { value: 'MH', label: 'Marshall Islands', icon: '🇲🇭' },
  { value: 'MK', label: 'North Macedonia', icon: '🇲🇰' },
  { value: 'ML', label: 'Mali', icon: '🇲🇱' },
  { value: 'MM', label: 'Myanmar', icon: '🇲🇲' },
  { value: 'MN', label: 'Mongolia', icon: '🇲🇳' },
  { value: 'MO', label: 'Macao', icon: '🇲🇴' },
  { value: 'MP', label: 'Northern Mariana Islands', icon: '🇲🇵' },
  { value: 'MQ', label: 'Martinique', icon: '🇲🇶' },
  { value: 'MR', label: 'Mauritania', icon: '🇲🇷' },
  { value: 'MS', label: 'Montserrat', icon: '🇲🇸' },
  { value: 'MT', label: 'Malta', icon: '🇲🇹' },
  { value: 'MU', label: 'Mauritius', icon: '🇲🇺' },
  { value: 'MV', label: 'Maldives', icon: '🇲🇻' },
  { value: 'MW', label: 'Malawi', icon: '🇲🇼' },
  { value: 'MX', label: 'Mexico', icon: '🇲🇽' },
  { value: 'MY', label: 'Malaysia', icon: '🇲🇾' },
  { value: 'MZ', label: 'Mozambique', icon: '🇲🇿' },
  { value: 'NA', label: 'Namibia', icon: '🇳🇦' },
  { value: 'NC', label: 'New Caledonia', icon: '🇳🇨' },
  { value: 'NE', label: 'Niger', icon: '🇳🇪' },
  { value: 'NF', label: 'Norfolk Island', icon: '🇳🇫' },
  { value: 'NG', label: 'Nigeria', icon: '🇳🇬' },
  { value: 'NI', label: 'Nicaragua', icon: '🇳🇮' },
  { value: 'NL', label: 'Netherlands', icon: '🇳🇱' },
  { value: 'NO', label: 'Norway', icon: '🇳🇴' },
  { value: 'NP', label: 'Nepal', icon: '🇳🇵' },
  { value: 'NR', label: 'Nauru', icon: '🇳🇷' },
  { value: 'NU', label: 'Niue', icon: '🇳🇺' },
  { value: 'NZ', label: 'New Zealand', icon: '🇳🇿' },
  { value: 'OM', label: 'Oman', icon: '🇴🇲' },
  { value: 'PA', label: 'Panama', icon: '🇵🇦' },
  { value: 'PE', label: 'Peru', icon: '🇵🇪' },
  { value: 'PF', label: 'French Polynesia', icon: '🇵🇫' },
  { value: 'PG', label: 'Papua New Guinea', icon: '🇵🇬' },
  { value: 'PH', label: 'Philippines', icon: '🇵🇭' },
  { value: 'PK', label: 'Pakistan', icon: '🇵🇰' },
  { value: 'PL', label: 'Poland', icon: '🇵🇱' },
  { value: 'PM', label: 'Saint Pierre and Miquelon', icon: '🇵🇲' },
  { value: 'PN', label: 'Pitcairn', icon: '🇵🇳' },
  { value: 'PR', label: 'Puerto Rico', icon: '🇵🇷' },
  { value: 'PT', label: 'Portugal', icon: '🇵🇹' },
  { value: 'PW', label: 'Palau', icon: '🇵🇼' },
  { value: 'PY', label: 'Paraguay', icon: '🇵🇾' },
  { value: 'QA', label: 'Qatar', icon: '🇶🇦' },
  { value: 'RE', label: 'Réunion', icon: '🇷🇪' },
  { value: 'RO', label: 'Romania', icon: '🇷🇴' },
  { value: 'RS', label: 'Serbia', icon: '🇷🇸' },
  { value: 'RU', label: 'Russian Federation', icon: '🇷🇺' },
  { value: 'RW', label: 'Rwanda', icon: '🇷🇼' },
  { value: 'SA', label: 'Saudi Arabia', icon: '🇸🇦' },
  { value: 'SB', label: 'Solomon Islands', icon: '🇸🇧' },
  { value: 'SC', label: 'Seychelles', icon: '🇸🇨' },
  { value: 'SD', label: 'Sudan', icon: '🇸🇩' },
  { value: 'SE', label: 'Sweden', icon: '🇸🇪' },
  { value: 'SG', label: 'Singapore', icon: '🇸🇬' },
  { value: 'SH', label: 'Saint Helena', icon: '🇸🇭' },
  { value: 'SI', label: 'Slovenia', icon: '🇸🇮' },
  { value: 'SJ', label: 'Svalbard and Jan Mayen', icon: '🇸🇯' },
  { value: 'SK', label: 'Slovakia', icon: '🇸🇰' },
  { value: 'SL', label: 'Sierra Leone', icon: '🇸🇱' },
  { value: 'SM', label: 'San Marino', icon: '🇸🇲' },
  { value: 'SN', label: 'Senegal', icon: '🇸🇳' },
  { value: 'SO', label: 'Somalia', icon: '🇸🇴' },
  { value: 'SR', label: 'Suriname', icon: '🇸🇷' },
  { value: 'SS', label: 'South Sudan', icon: '🇸🇸' },
  { value: 'ST', label: 'Sao Tome and Principe', icon: '🇸🇹' },
  { value: 'SV', label: 'El Salvador', icon: '🇸🇻' },
  { value: 'SX', label: 'Sint Maarten (Dutch part)', icon: '🇸🇽' },
  { value: 'SY', label: 'Syrian Arab Republic', icon: '🇸🇾' },
  { value: 'SZ', label: 'Eswatini', icon: '🇸🇿' },
  { value: 'TC', label: 'Turks and Caicos Islands', icon: '🇹🇨' },
  { value: 'TD', label: 'Chad', icon: '🇹🇩' },
  { value: 'TF', label: 'French Southern Territories', icon: '🇹🇫' },
  { value: 'TG', label: 'Togo', icon: '🇹🇬' },
  { value: 'TH', label: 'Thailand', icon: '🇹🇭' },
  { value: 'TJ', label: 'Tajikistan', icon: '🇹🇯' },
  { value: 'TK', label: 'Tokelau', icon: '🇹🇰' },
  { value: 'TL', label: 'Timor-Leste', icon: '🇹🇱' },
  { value: 'TM', label: 'Turkmenistan', icon: '🇹🇲' },
  { value: 'TN', label: 'Tunisia', icon: '🇹🇳' },
  { value: 'TO', label: 'Tonga', icon: '🇹🇴' },
  { value: 'TR', label: 'Turkey', icon: '🇹🇷' },
  { value: 'TT', label: 'Trinidad and Tobago', icon: '🇹🇹' },
  { value: 'TV', label: 'Tuvalu', icon: '🇹🇻' },
  { value: 'TZ', label: 'Tanzania, United Republic of', icon: '🇹🇿' },
  { value: 'UA', label: 'Ukraine', icon: '🇺🇦' },
  { value: 'UG', label: 'Uganda', icon: '🇺🇬' },
  { value: 'UM', label: 'United States Minor Outlying Islands', icon: '🇺🇲' },
  { value: 'US', label: 'United States of America', icon: '🇺🇸' },
  { value: 'UY', label: 'Uruguay', icon: '🇺🇾' },
  { value: 'UZ', label: 'Uzbekistan', icon: '🇺🇿' },
  { value: 'VA', label: 'Holy See (Vatican City State)', icon: '🇻🇦' },
  { value: 'VC', label: 'Saint Vincent and the Grenadines', icon: '🇻🇨' },
  { value: 'VE', label: 'Venezuela (Bolivarian Republic of)', icon: '🇻🇪' },
  { value: 'VG', label: 'Virgin Islands (British)', icon: '🇻🇬' },
  { value: 'VI', label: 'Virgin Islands (U.S.)', icon: '🇻🇮' },
  { value: 'VN', label: 'Vietnam', icon: '🇻🇳' },
  { value: 'VU', label: 'Vanuatu', icon: '🇻🇺' },
  { value: 'WF', label: 'Wallis and Futuna', icon: '🇼🇫' },
  { value: 'WS', label: 'Samoa', icon: '🇼🇸' },
  { value: 'YE', label: 'Yemen', icon: '🇾🇪' },
  { value: 'YT', label: 'Mayotte', icon: '🇾🇹' },
  { value: 'ZA', label: 'South Africa', icon: '🇿🇦' },
  { value: 'ZM', label: 'Zambia', icon: '🇿🇲' },
  { value: 'ZW', label: 'Zimbabwe', icon: '🇿🇼' },
];

export const adType = [
  {
    value: 'facebook',
    label: 'Facebook',
    icon: 'ant-design:facebook-outlined',
  },
  { value: 'google', label: 'Google', icon: 'ant-design:google-outlined' },
  { value: 'tiktok', label: 'Tiktok', icon: 'ant-design:tik-tok-outlined' },
];

export enum ECogsSource {
  MANUAL = 'manual',
  SHOPIFY = 'shopify',
}

export const cogsSoures = [
  {
    value: ECogsSource.MANUAL,
    labelKey: 'page.settings-cogs.option.manual',
    label: 'Manual',
  },
  {
    value: ECogsSource.SHOPIFY,
    labelKey: 'page.settings-cogs.option.shopify',
    label: 'Shopify',
  },
];

export const timezones = [
  'Africa/Abidjan',
  'Africa/Accra',
  'Africa/Addis_Ababa',
  'Africa/Algiers',
  'Africa/Asmara',
  'Africa/Asmera',
  'Africa/Bamako',
  'Africa/Bangui',
  'Africa/Banjul',
  'Africa/Bissau',
  'Africa/Blantyre',
  'Africa/Brazzaville',
  'Africa/Bujumbura',
  'Africa/Cairo',
  'Africa/Casablanca',
  'Africa/Ceuta',
  'Africa/Conakry',
  'Africa/Dakar',
  'Africa/Dar_es_Salaam',
  'Africa/Djibouti',
  'Africa/Douala',
  'Africa/El_Aaiun',
  'Africa/Freetown',
  'Africa/Gaborone',
  'Africa/Harare',
  'Africa/Johannesburg',
  'Africa/Juba',
  'Africa/Kampala',
  'Africa/Khartoum',
  'Africa/Kigali',
  'Africa/Kinshasa',
  'Africa/Lagos',
  'Africa/Libreville',
  'Africa/Lome',
  'Africa/Luanda',
  'Africa/Lubumbashi',
  'Africa/Lusaka',
  'Africa/Malabo',
  'Africa/Maputo',
  'Africa/Maseru',
  'Africa/Mbabane',
  'Africa/Mogadishu',
  'Africa/Monrovia',
  'Africa/Nairobi',
  'Africa/Ndjamena',
  'Africa/Niamey',
  'Africa/Nouakchott',
  'Africa/Ouagadougou',
  'Africa/Porto-Novo',
  'Africa/Sao_Tome',
  'Africa/Timbuktu',
  'Africa/Tripoli',
  'Africa/Tunis',
  'Africa/Windhoek',
  'America/Adak',
  'America/Anchorage',
  'America/Anguilla',
  'America/Antigua',
  'America/Araguaina',
  'America/Argentina/Buenos_Aires',
  'America/Argentina/Catamarca',
  'America/Argentina/ComodRivadavia',
  'America/Argentina/Cordoba',
  'America/Argentina/Jujuy',
  'America/Argentina/La_Rioja',
  'America/Argentina/Mendoza',
  'America/Argentina/Rio_Gallegos',
  'America/Argentina/Salta',
  'America/Argentina/San_Juan',
  'America/Argentina/San_Luis',
  'America/Argentina/Tucuman',
  'America/Argentina/Ushuaia',
  'America/Aruba',
  'America/Asuncion',
  'America/Atikokan',
  'America/Atka',
  'America/Bahia',
  'America/Bahia_Banderas',
  'America/Barbados',
  'America/Belem',
  'America/Belize',
  'America/Blanc-Sablon',
  'America/Boa_Vista',
  'America/Bogota',
  'America/Boise',
  'America/Buenos_Aires',
  'America/Cambridge_Bay',
  'America/Campo_Grande',
  'America/Cancun',
  'America/Caracas',
  'America/Catamarca',
  'America/Cayenne',
  'America/Cayman',
  'America/Chicago',
  'America/Chihuahua',
  'America/Coral_Harbour',
  'America/Cordoba',
  'America/Costa_Rica',
  'America/Creston',
  'America/Cuiaba',
  'America/Curacao',
  'America/Danmarkshavn',
  'America/Dawson',
  'America/Dawson_Creek',
  'America/Denver',
  'America/Detroit',
  'America/Dominica',
  'America/Edmonton',
  'America/Eirunepe',
  'America/El_Salvador',
  'America/Ensenada',
  'America/Fort_Nelson',
  'America/Fort_Wayne',
  'America/Fortaleza',
  'America/Glace_Bay',
  'America/Godthab',
  'America/Goose_Bay',
  'America/Grand_Turk',
  'America/Grenada',
  'America/Guadeloupe',
  'America/Guatemala',
  'America/Guayaquil',
  'America/Guyana',
  'America/Halifax',
  'America/Havana',
  'America/Hermosillo',
  'America/Indiana/Indianapolis',
  'America/Indiana/Knox',
  'America/Indiana/Marengo',
  'America/Indiana/Petersburg',
  'America/Indiana/Tell_City',
  'America/Indiana/Vevay',
  'America/Indiana/Vincennes',
  'America/Indiana/Winamac',
  'America/Indianapolis',
  'America/Inuvik',
  'America/Iqaluit',
  'America/Jamaica',
  'America/Jujuy',
  'America/Juneau',
  'America/Kentucky/Louisville',
  'America/Kentucky/Monticello',
  'America/Knox_IN',
  'America/Kralendijk',
  'America/La_Paz',
  'America/Lima',
  'America/Los_Angeles',
  'America/Louisville',
  'America/Lower_Princes',
  'America/Maceio',
  'America/Managua',
  'America/Manaus',
  'America/Marigot',
  'America/Martinique',
  'America/Matamoros',
  'America/Mazatlan',
  'America/Mendoza',
  'America/Menominee',
  'America/Merida',
  'America/Metlakatla',
  'America/Mexico_City',
  'America/Miquelon',
  'America/Moncton',
  'America/Monterrey',
  'America/Montevideo',
  'America/Montreal',
  'America/Montserrat',
  'America/Nassau',
  'America/New_York',
  'America/Nipigon',
  'America/Nome',
  'America/Noronha',
  'America/North_Dakota/Beulah',
  'America/North_Dakota/Center',
  'America/North_Dakota/New_Salem',
  'America/Nuuk',
  'America/Ojinaga',
  'America/Panama',
  'America/Pangnirtung',
  'America/Paramaribo',
  'America/Phoenix',
  'America/Port-au-Prince',
  'America/Port_of_Spain',
  'America/Porto_Acre',
  'America/Porto_Velho',
  'America/Puerto_Rico',
  'America/Punta_Arenas',
  'America/Rainy_River',
  'America/Rankin_Inlet',
  'America/Recife',
  'America/Regina',
  'America/Resolute',
  'America/Rio_Branco',
  'America/Rosario',
  'America/Santa_Isabel',
  'America/Santarem',
  'America/Santiago',
  'America/Santo_Domingo',
  'America/Sao_Paulo',
  'America/Scoresbysund',
  'America/Shiprock',
  'America/Sitka',
  'America/St_Barthelemy',
  'America/St_Johns',
  'America/St_Kitts',
  'America/St_Lucia',
  'America/St_Thomas',
  'America/St_Vincent',
  'America/Swift_Current',
  'America/Tegucigalpa',
  'America/Thule',
  'America/Thunder_Bay',
  'America/Tijuana',
  'America/Toronto',
  'America/Tortola',
  'America/Vancouver',
  'America/Virgin',
  'America/Whitehorse',
  'America/Winnipeg',
  'America/Yakutat',
  'America/Yellowknife',
  'Antarctica/Casey',
  'Antarctica/Davis',
  'Antarctica/DumontDUrville',
  'Antarctica/Macquarie',
  'Antarctica/Mawson',
  'Antarctica/McMurdo',
  'Antarctica/Palmer',
  'Antarctica/Rothera',
  'Antarctica/South_Pole',
  'Antarctica/Syowa',
  'Antarctica/Troll',
  'Antarctica/Vostok',
  'Arctic/Longyearbyen',
  'Asia/Aden',
  'Asia/Almaty',
  'Asia/Amman',
  'Asia/Anadyr',
  'Asia/Aqtau',
  'Asia/Aqtobe',
  'Asia/Ashgabat',
  'Asia/Ashkhabad',
  'Asia/Atyrau',
  'Asia/Baghdad',
  'Asia/Bahrain',
  'Asia/Baku',
  'Asia/Bangkok',
  'Asia/Barnaul',
  'Asia/Beirut',
  'Asia/Bishkek',
  'Asia/Brunei',
  'Asia/Calcutta',
  'Asia/Chita',
  'Asia/Choibalsan',
  'Asia/Chongqing',
  'Asia/Chungking',
  'Asia/Colombo',
  'Asia/Dacca',
  'Asia/Damascus',
  'Asia/Dhaka',
  'Asia/Dili',
  'Asia/Dubai',
  'Asia/Dushanbe',
  'Asia/Famagusta',
  'Asia/Gaza',
  'Asia/Harbin',
  'Asia/Hebron',
  'Asia/Ho_Chi_Minh',
  'Asia/Hong_Kong',
  'Asia/Hovd',
  'Asia/Irkutsk',
  'Asia/Istanbul',
  'Asia/Jakarta',
  'Asia/Jayapura',
  'Asia/Jerusalem',
  'Asia/Kabul',
  'Asia/Kamchatka',
  'Asia/Karachi',
  'Asia/Kashgar',
  'Asia/Kathmandu',
  'Asia/Katmandu',
  'Asia/Khandyga',
  'Asia/Kolkata',
  'Asia/Krasnoyarsk',
  'Asia/Kuala_Lumpur',
  'Asia/Kuching',
  'Asia/Kuwait',
  'Asia/Macao',
  'Asia/Macau',
  'Asia/Magadan',
  'Asia/Makassar',
  'Asia/Manila',
  'Asia/Muscat',
  'Asia/Nicosia',
  'Asia/Novokuznetsk',
  'Asia/Novosibirsk',
  'Asia/Omsk',
  'Asia/Oral',
  'Asia/Phnom_Penh',
  'Asia/Pontianak',
  'Asia/Pyongyang',
  'Asia/Qatar',
  'Asia/Qostanay',
  'Asia/Qyzylorda',
  'Asia/Rangoon',
  'Asia/Riyadh',
  'Asia/Saigon',
  'Asia/Sakhalin',
  'Asia/Samarkand',
  'Asia/Seoul',
  'Asia/Shanghai',
  'Asia/Singapore',
  'Asia/Srednekolymsk',
  'Asia/Taipei',
  'Asia/Tashkent',
  'Asia/Tbilisi',
  'Asia/Tehran',
  'Asia/Tel_Aviv',
  'Asia/Thimbu',
  'Asia/Thimphu',
  'Asia/Tokyo',
  'Asia/Tomsk',
  'Asia/Ujung_Pandang',
  'Asia/Ulaanbaatar',
  'Asia/Ulan_Bator',
  'Asia/Urumqi',
  'Asia/Ust-Nera',
  'Asia/Vientiane',
  'Asia/Vladivostok',
  'Asia/Yakutsk',
  'Asia/Yangon',
  'Asia/Yekaterinburg',
  'Asia/Yerevan',
  'Atlantic/Azores',
  'Atlantic/Bermuda',
  'Atlantic/Canary',
  'Atlantic/Cape_Verde',
  'Atlantic/Faeroe',
  'Atlantic/Faroe',
  'Atlantic/Jan_Mayen',
  'Atlantic/Madeira',
  'Atlantic/Reykjavik',
  'Atlantic/South_Georgia',
  'Atlantic/St_Helena',
  'Atlantic/Stanley',
  'Australia/ACT',
  'Australia/Adelaide',
  'Australia/Brisbane',
  'Australia/Broken_Hill',
  'Australia/Canberra',
  'Australia/Currie',
  'Australia/Darwin',
  'Australia/Eucla',
  'Australia/Hobart',
  'Australia/LHI',
  'Australia/Lindeman',
  'Australia/Lord_Howe',
  'Australia/Melbourne',
  'Australia/NSW',
  'Australia/North',
  'Australia/Perth',
  'Australia/Queensland',
  'Australia/South',
  'Australia/Sydney',
  'Australia/Tasmania',
  'Australia/Victoria',
  'Australia/West',
  'Australia/Yancowinna',
  'Brazil/Acre',
  'Brazil/DeNoronha',
  'Brazil/East',
  'Brazil/West',
  'CET',
  'CST6CDT',
  'Canada/Atlantic',
  'Canada/Central',
  'Canada/Eastern',
  'Canada/Mountain',
  'Canada/Newfoundland',
  'Canada/Pacific',
  'Canada/Saskatchewan',
  'Canada/Yukon',
  'Chile/Continental',
  'Chile/EasterIsland',
  'Cuba',
  'EET',
  'EST',
  'EST5EDT',
  'Egypt',
  'Eire',
  'Etc/GMT',
  'Etc/GMT+0',
  'Etc/GMT+1',
  'Etc/GMT+10',
  'Etc/GMT+11',
  'Etc/GMT+12',
  'Etc/GMT+2',
  'Etc/GMT+3',
  'Etc/GMT+4',
  'Etc/GMT+5',
  'Etc/GMT+6',
  'Etc/GMT+7',
  'Etc/GMT+8',
  'Etc/GMT+9',
  'Etc/GMT-0',
  'Etc/GMT-1',
  'Etc/GMT-10',
  'Etc/GMT-11',
  'Etc/GMT-12',
  'Etc/GMT-13',
  'Etc/GMT-14',
  'Etc/GMT-2',
  'Etc/GMT-3',
  'Etc/GMT-4',
  'Etc/GMT-5',
  'Etc/GMT-6',
  'Etc/GMT-7',
  'Etc/GMT-8',
  'Etc/GMT-9',
  'Etc/GMT0',
  'Etc/Greenwich',
  'Etc/UCT',
  'Etc/UTC',
  'Etc/Universal',
  'Etc/Zulu',
  'Europe/Amsterdam',
  'Europe/Andorra',
  'Europe/Astrakhan',
  'Europe/Athens',
  'Europe/Belfast',
  'Europe/Belgrade',
  'Europe/Berlin',
  'Europe/Bratislava',
  'Europe/Brussels',
  'Europe/Bucharest',
  'Europe/Budapest',
  'Europe/Busingen',
  'Europe/Chisinau',
  'Europe/Copenhagen',
  'Europe/Dublin',
  'Europe/Gibraltar',
  'Europe/Guernsey',
  'Europe/Helsinki',
  'Europe/Isle_of_Man',
  'Europe/Istanbul',
  'Europe/Jersey',
  'Europe/Kaliningrad',
  'Europe/Kiev',
  'Europe/Kirov',
  'Europe/Lisbon',
  'Europe/Ljubljana',
  'Europe/London',
  'Europe/Luxembourg',
  'Europe/Madrid',
  'Europe/Malta',
  'Europe/Mariehamn',
  'Europe/Minsk',
  'Europe/Monaco',
  'Europe/Moscow',
  'Europe/Nicosia',
  'Europe/Oslo',
  'Europe/Paris',
  'Europe/Podgorica',
  'Europe/Prague',
  'Europe/Riga',
  'Europe/Rome',
  'Europe/Samara',
  'Europe/San_Marino',
  'Europe/Sarajevo',
  'Europe/Saratov',
  'Europe/Simferopol',
  'Europe/Skopje',
  'Europe/Sofia',
  'Europe/Stockholm',
  'Europe/Tallinn',
  'Europe/Tirane',
  'Europe/Tiraspol',
  'Europe/Ulyanovsk',
  'Europe/Uzhgorod',
  'Europe/Vaduz',
  'Europe/Vatican',
  'Europe/Vienna',
  'Europe/Vilnius',
  'Europe/Volgograd',
  'Europe/Warsaw',
  'Europe/Zagreb',
  'Europe/Zaporozhye',
  'Europe/Zurich',
  'GB',
  'GB-Eire',
  'GMT',
  'GMT+0',
  'GMT-0',
  'GMT0',
  'Greenwich',
  'HST',
  'Hongkong',
  'Iceland',
  'Indian/Antananarivo',
  'Indian/Chagos',
  'Indian/Christmas',
  'Indian/Cocos',
  'Indian/Comoro',
  'Indian/Kerguelen',
  'Indian/Mahe',
  'Indian/Maldives',
  'Indian/Mauritius',
  'Indian/Mayotte',
  'Indian/Reunion',
  'Iran',
  'Israel',
  'Jamaica',
  'Japan',
  'Kwajalein',
  'Libya',
  'MET',
  'MST',
  'MST7MDT',
  'Mexico/BajaNorte',
  'Mexico/BajaSur',
  'Mexico/General',
  'NZ',
  'NZ-CHAT',
  'Navajo',
  'PRC',
  'PST8PDT',
  'Pacific/Apia',
  'Pacific/Auckland',
  'Pacific/Bougainville',
  'Pacific/Chatham',
  'Pacific/Chuuk',
  'Pacific/Easter',
  'Pacific/Efate',
  'Pacific/Enderbury',
  'Pacific/Fakaofo',
  'Pacific/Fiji',
  'Pacific/Funafuti',
  'Pacific/Galapagos',
  'Pacific/Gambier',
  'Pacific/Guadalcanal',
  'Pacific/Guam',
  'Pacific/Honolulu',
  'Pacific/Johnston',
  'Pacific/Kanton',
  'Pacific/Kiritimati',
  'Pacific/Kosrae',
  'Pacific/Kwajalein',
  'Pacific/Majuro',
  'Pacific/Marquesas',
  'Pacific/Midway',
  'Pacific/Nauru',
  'Pacific/Niue',
  'Pacific/Norfolk',
  'Pacific/Noumea',
  'Pacific/Pago_Pago',
  'Pacific/Palau',
  'Pacific/Pitcairn',
  'Pacific/Pohnpei',
  'Pacific/Ponape',
  'Pacific/Port_Moresby',
  'Pacific/Rarotonga',
  'Pacific/Saipan',
  'Pacific/Samoa',
  'Pacific/Tahiti',
  'Pacific/Tarawa',
  'Pacific/Tongatapu',
  'Pacific/Truk',
  'Pacific/Wake',
  'Pacific/Wallis',
  'Pacific/Yap',
  'Poland',
  'Portugal',
  'ROC',
  'ROK',
  'Singapore',
  'Turkey',
  'UCT',
  'US/Alaska',
  'US/Aleutian',
  'US/Arizona',
  'US/Central',
  'US/East-Indiana',
  'US/Eastern',
  'US/Hawaii',
  'US/Indiana-Starke',
  'US/Michigan',
  'US/Mountain',
  'US/Pacific',
  'US/Samoa',
  'UTC',
  'Universal',
  'W-SU',
  'WET',
  'Zulu',
];
